from __future__ import annotations

"""Safe, data-only material packs for the Qt user interface.

Material packs deliberately are *not* Qt stylesheets.  A package may contain a
strict JSON manifest and, optionally, one raster background.  All Qt CSS is
generated by this module from validated colour tokens, so importing a pack can
never introduce a script, an arbitrary URL, or a QSS selector.
"""

from dataclasses import dataclass
import json
import os
from pathlib import Path, PurePosixPath
import re
import stat
import tempfile
from typing import Literal
import unicodedata
import zipfile

from pydantic import BaseModel, ConfigDict, Field, ValidationError, field_validator, model_validator


PACK_EXTENSION = ".aifopack"
MANIFEST_NAME = "manifest.json"
PACK_FORMAT_VERSION = 1
MAX_ARCHIVE_BYTES = 12 * 1024 * 1024
MAX_MANIFEST_BYTES = 64 * 1024
MAX_BACKGROUND_BYTES = 10 * 1024 * 1024
MAX_TOTAL_UNPACKED_BYTES = 11 * 1024 * 1024
MAX_ARCHIVE_ENTRIES = 3
MAX_COMPRESSION_RATIO = 100.0
MAX_IMAGE_DIMENSION = 8192
MAX_IMAGE_PIXELS = 32_000_000

_PACK_ID_RE = re.compile(r"^[a-z0-9][a-z0-9_-]{0,63}$")
_VERSION_RE = re.compile(r"^[0-9]+(?:\.[0-9]+){0,3}$")
_COLOR_RE = re.compile(r"^#[0-9A-Fa-f]{6}$")
_BACKGROUND_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9_. -]{0,127}\.(?:png|jpe?g|webp)$", re.I)
_WINDOWS_RESERVED = {
    "con", "prn", "aux", "nul", *(f"com{i}" for i in range(1, 10)),
    *(f"lpt{i}" for i in range(1, 10)),
}


def _rgba(value: str) -> tuple[float, float, float, float]:
    raw = value.removeprefix("#")
    alpha = int(raw[6:8], 16) / 255 if len(raw) == 8 else 1.0
    return tuple(int(raw[index:index + 2], 16) / 255 for index in (0, 2, 4)) + (alpha,)


def _blend(value: str, background: tuple[float, float, float]) -> tuple[float, float, float]:
    red, green, blue, alpha = _rgba(value)
    return tuple(alpha * foreground + (1 - alpha) * behind for foreground, behind in zip((red, green, blue), background))


def _luminance(rgb: tuple[float, float, float]) -> float:
    channels = tuple(value / 12.92 if value <= 0.04045 else ((value + 0.055) / 1.055) ** 2.4 for value in rgb)
    return 0.2126 * channels[0] + 0.7152 * channels[1] + 0.0722 * channels[2]


def _contrast(foreground: str, background: tuple[float, float, float]) -> float:
    foreground_luminance = _luminance(_blend(foreground, background))
    background_luminance = _luminance(background)
    lighter, darker = max(foreground_luminance, background_luminance), min(foreground_luminance, background_luminance)
    return (lighter + 0.05) / (darker + 0.05)


class MaterialPackError(RuntimeError):
    """Base error suitable for displaying in a settings dialog."""


class UnsafeMaterialPack(MaterialPackError):
    """The package failed a security or resource-limit check."""


class MaterialPackNotFound(MaterialPackError):
    """The requested material pack does not exist."""


class ColorTokens(BaseModel):
    """The only values a material pack may feed into generated QSS."""

    model_config = ConfigDict(extra="forbid", strict=True, frozen=True)

    window: str
    panel: str
    elevated: str
    input: str
    text: str
    muted_text: str
    accent: str
    accent_hover: str
    accent_pressed: str
    border: str
    selection_text: str
    success: str
    warning: str
    danger: str

    @field_validator("*")
    @classmethod
    def validate_colour(cls, value: str) -> str:
        if not _COLOR_RE.fullmatch(value):
            raise ValueError("颜色必须使用 #RRGGBB（不接受透明通道）")
        return value.upper()


class MaterialManifest(BaseModel):
    """Strict, versioned and data-only on-disk package manifest."""

    model_config = ConfigDict(extra="forbid", strict=True, frozen=True)

    format_version: Literal[1] = PACK_FORMAT_VERSION
    id: str = Field(min_length=1, max_length=64)
    name: str = Field(min_length=1, max_length=80)
    version: str = Field(default="1.0", min_length=1, max_length=24)
    author: str = Field(default="", max_length=80)
    description: str = Field(default="", max_length=500)
    colors: ColorTokens
    background: str | None = None
    background_mode: Literal["cover", "tile", "center"] = "cover"

    @field_validator("id")
    @classmethod
    def valid_id(cls, value: str) -> str:
        if not _PACK_ID_RE.fullmatch(value):
            raise ValueError("材质包 ID 只能包含小写字母、数字、下划线和连字符")
        if value in {".", ".."}:
            raise ValueError("材质包 ID 无效")
        return value

    @field_validator("name")
    @classmethod
    def nonempty_safe_name(cls, value: str) -> str:
        value = value.strip()
        if not value:
            raise ValueError("材质包名称不能为空")
        if any(unicodedata.category(char) in {"Cc", "Cf", "Cs"} for char in value) or any(char in "<>&" for char in value):
            raise ValueError("材质包名称必须是安全的单行纯文本")
        return value

    @field_validator("author", "description")
    @classmethod
    def safe_metadata(cls, value: str) -> str:
        value = value.strip()
        if any(unicodedata.category(char) in {"Cc", "Cf", "Cs"} for char in value):
            raise ValueError("文本包含控制字符")
        return value

    @field_validator("version")
    @classmethod
    def valid_version(cls, value: str) -> str:
        if not _VERSION_RE.fullmatch(value):
            raise ValueError("版本号格式无效")
        return value

    @field_validator("background")
    @classmethod
    def valid_background_name(cls, value: str | None) -> str | None:
        if value is None:
            return None
        if not _BACKGROUND_RE.fullmatch(value):
            raise ValueError("背景必须是包根目录下的 PNG、JPG 或 WebP 文件")
        _validate_member_name(value)
        return value

    @model_validator(mode="after")
    def readable_colours(self) -> "MaterialManifest":
        colors = self.colors
        if _rgba(colors.window)[3] < 0.95:
            raise ValueError("窗口背景不能高度透明")
        white = (1.0, 1.0, 1.0)
        window = _blend(colors.window, white)
        panel = _blend(colors.panel, window)
        elevated = _blend(colors.elevated, panel)
        input_background = _blend(colors.input, panel)
        text_backgrounds = (window, panel, elevated, input_background)
        if min(_contrast(colors.text, background) for background in text_backgrounds) < 4.5:
            raise ValueError("正文颜色与界面背景的对比度不足")
        if min(_contrast(colors.muted_text, background) for background in (window, panel)) < 3.0:
            raise ValueError("辅助文字颜色与背景的对比度不足")
        if min(_contrast(colors.selection_text, _blend(accent, panel)) for accent in (colors.accent, colors.accent_hover, colors.accent_pressed)) < 4.5:
            raise ValueError("按钮/选择文字与强调色的对比度不足")
        if min(_contrast(colors.border, background) for background in (window, panel, input_background)) < 2.5:
            raise ValueError("边框颜色与背景的对比度不足")
        for status in (colors.success, colors.warning, colors.danger):
            if min(_contrast(status, background) for background in (window, panel)) < 3.0:
                raise ValueError("状态颜色与背景的对比度不足")
        return self


class MaterialPack(BaseModel):
    """A resolved built-in or user-installed material pack."""

    model_config = ConfigDict(extra="forbid", strict=True, frozen=True)

    manifest: MaterialManifest
    source: Literal["builtin", "custom"]
    directory: Path | None = None
    background_path: Path | None = None

    @property
    def id(self) -> str:
        return self.manifest.id

    @property
    def name(self) -> str:
        return self.manifest.name


@dataclass(frozen=True)
class AppliedMaterial:
    pack: MaterialPack
    stylesheet: str

    @property
    def id(self) -> str:
        return self.pack.id


def _tokens(**values: str) -> ColorTokens:
    return ColorTokens.model_validate(values)


_BUILTIN_MANIFESTS: tuple[MaterialManifest, ...] = (
    MaterialManifest(
        id="default", name="Windows 黑白", author="AI File Organizer",
        description="使用原生 Windows 黑白系统控件，不附加自定义界面样式。",
        colors=_tokens(
            window="#F4F6F8", panel="#FFFFFF", elevated="#FFFFFF", input="#FFFFFF",
            text="#20242A", muted_text="#667085", accent="#2F6FED", accent_hover="#245FD1",
            accent_pressed="#1C4BA8", border="#8A94A3", selection_text="#FFFFFF",
            success="#198754", warning="#B7791F", danger="#C0392B",
        ),
    ),
    MaterialManifest(
        id="dark", name="深色", author="AI File Organizer",
        description="适合低光环境的深色材质。",
        colors=_tokens(
            window="#171A1F", panel="#20242B", elevated="#292E37", input="#15181D",
            text="#F2F4F7", muted_text="#A5ADBA", accent="#6EA8FE", accent_hover="#8BBBFF",
            accent_pressed="#4C8DE8", border="#667085", selection_text="#101318",
            success="#58C78B", warning="#F1C75B", danger="#FF7B72",
        ),
    ),
    MaterialManifest(
        id="ocean", name="海洋", author="AI File Organizer",
        description="冷静的海蓝色材质。",
        colors=_tokens(
            window="#EAF4F8", panel="#F8FCFD", elevated="#FFFFFF", input="#FFFFFF",
            text="#17324D", muted_text="#55738B", accent="#087EA4", accent_hover="#066B8C",
            accent_pressed="#055670", border="#668898", selection_text="#FFFFFF",
            success="#158467", warning="#AD720F", danger="#C54848",
        ),
    ),
    MaterialManifest(
        id="warm", name="暖色", author="AI File Organizer",
        description="柔和的暖色纸张质感。",
        colors=_tokens(
            window="#F8F1E7", panel="#FFF9F0", elevated="#FFFDF8", input="#FFFCF6",
            text="#3D3028", muted_text="#796A60", accent="#B65C35", accent_hover="#9C4D2C",
            accent_pressed="#7E3E25", border="#9F8068", selection_text="#FFFFFF",
            success="#4F7B4A", warning="#A56B19", danger="#B6453D",
        ),
    ),
)
BUILTIN_IDS = frozenset(item.id for item in _BUILTIN_MANIFESTS)


def builtin_materials() -> tuple[MaterialPack, ...]:
    return tuple(MaterialPack(manifest=item, source="builtin") for item in _BUILTIN_MANIFESTS)


def _validate_member_name(name: str) -> None:
    if not name or "\x00" in name or "\\" in name or unicodedata.normalize("NFC", name) != name:
        raise UnsafeMaterialPack("材质包包含不安全的文件名")
    pure = PurePosixPath(name)
    if pure.is_absolute() or len(pure.parts) != 1 or pure.parts[0] in {".", ".."} or ":" in name:
        raise UnsafeMaterialPack("材质包文件必须位于包根目录")
    # Windows treats a device name as reserved even when more extensions are
    # appended (for example ``CON.photo.png``).
    base = pure.name.split(".", 1)[0].rstrip(" .").casefold()
    if base in _WINDOWS_RESERVED or name[-1:] in {" ", "."}:
        raise UnsafeMaterialPack("材质包包含系统保留文件名")


def _is_link_like(path: Path) -> bool:
    try:
        status = path.lstat()
    except FileNotFoundError:
        return False
    attrs = getattr(status, "st_file_attributes", 0)
    reparse = getattr(stat, "FILE_ATTRIBUTE_REPARSE_POINT", 0)
    return path.is_symlink() or bool(attrs & reparse)


def _guard_storage_root(root: Path) -> Path:
    root = root.expanduser()
    if root.exists() and (_is_link_like(root) or not root.is_dir()):
        raise UnsafeMaterialPack("材质包目录不是安全的普通目录")
    root.mkdir(parents=True, exist_ok=True)
    if _is_link_like(root) or not root.is_dir():
        raise UnsafeMaterialPack("材质包目录不是安全的普通目录")
    return root.resolve()


def _zip_entry_is_link(info: zipfile.ZipInfo) -> bool:
    unix_mode = (info.external_attr >> 16) & 0xFFFF
    file_type = stat.S_IFMT(unix_mode)
    if file_type not in {0, stat.S_IFREG}:
        return True
    # Reject a DOS directory bit without a trailing slash as well as Windows'
    # FILE_ATTRIBUTE_REPARSE_POINT bit.
    return bool(info.external_attr & (0x10 | 0x400))


def _read_bounded(handle: object, limit: int) -> bytes:
    data = handle.read(limit + 1)  # type: ignore[attr-defined]
    if len(data) > limit:
        raise UnsafeMaterialPack("材质包文件超过大小限制")
    return data


def _parse_manifest(raw: bytes) -> MaterialManifest:
    def unique_object(pairs: list[tuple[str, object]]) -> dict[str, object]:
        result: dict[str, object] = {}
        for key, value in pairs:
            if key in result:
                raise UnsafeMaterialPack(f"manifest.json 包含重复字段：{key}")
            result[key] = value
        return result

    def reject_constant(item: str) -> object:
        raise UnsafeMaterialPack(f"manifest.json 包含无效数值：{item}")

    try:
        decoded = raw.decode("utf-8", errors="strict")
        value = json.loads(
            decoded,
            object_pairs_hook=unique_object,
            parse_constant=reject_constant,
        )
    except UnicodeDecodeError as exc:
        raise UnsafeMaterialPack("manifest.json 必须使用 UTF-8") from exc
    if not isinstance(value, dict):
        raise UnsafeMaterialPack("manifest.json 顶层必须是对象")
    return MaterialManifest.model_validate(value, strict=True)


def _image_dimensions(data: bytes, suffix: str) -> tuple[int, int]:
    suffix = suffix.casefold()
    if suffix == ".png":
        if len(data) < 24 or data[:8] != b"\x89PNG\r\n\x1a\n" or data[12:16] != b"IHDR":
            raise UnsafeMaterialPack("PNG 背景文件格式无效")
        return int.from_bytes(data[16:20], "big"), int.from_bytes(data[20:24], "big")
    if suffix in {".jpg", ".jpeg"}:
        if len(data) < 4 or data[:2] != b"\xff\xd8":
            raise UnsafeMaterialPack("JPEG 背景文件格式无效")
        offset = 2
        sof = {0xC0, 0xC1, 0xC2, 0xC3, 0xC5, 0xC6, 0xC7, 0xC9, 0xCA, 0xCB, 0xCD, 0xCE, 0xCF}
        while offset + 4 <= len(data):
            if data[offset] != 0xFF:
                offset += 1
                continue
            while offset < len(data) and data[offset] == 0xFF:
                offset += 1
            if offset >= len(data):
                break
            marker = data[offset]
            offset += 1
            if marker in {0xD8, 0xD9} or 0xD0 <= marker <= 0xD7:
                continue
            if offset + 2 > len(data):
                break
            length = int.from_bytes(data[offset:offset + 2], "big")
            if length < 2 or offset + length > len(data):
                break
            if marker in sof and length >= 7:
                return (
                    int.from_bytes(data[offset + 5:offset + 7], "big"),
                    int.from_bytes(data[offset + 3:offset + 5], "big"),
                )
            offset += length
        raise UnsafeMaterialPack("无法读取 JPEG 背景尺寸")
    if suffix == ".webp":
        if len(data) < 30 or data[:4] != b"RIFF" or data[8:12] != b"WEBP":
            raise UnsafeMaterialPack("WebP 背景文件格式无效")
        kind = data[12:16]
        if kind == b"VP8X":
            return 1 + int.from_bytes(data[24:27], "little"), 1 + int.from_bytes(data[27:30], "little")
        if kind == b"VP8L" and data[20] == 0x2F:
            bits = int.from_bytes(data[21:25], "little")
            return (bits & 0x3FFF) + 1, ((bits >> 14) & 0x3FFF) + 1
        if kind == b"VP8 " and len(data) >= 30 and data[23:26] == b"\x9d\x01\x2a":
            return int.from_bytes(data[26:28], "little") & 0x3FFF, int.from_bytes(data[28:30], "little") & 0x3FFF
        raise UnsafeMaterialPack("无法读取 WebP 背景尺寸")
    raise UnsafeMaterialPack("不支持的背景图片格式")


def _validate_image(data: bytes, filename: str) -> None:
    width, height = _image_dimensions(data, Path(filename).suffix)
    if width <= 0 or height <= 0:
        raise UnsafeMaterialPack("背景图片尺寸无效")
    if width > MAX_IMAGE_DIMENSION or height > MAX_IMAGE_DIMENSION or width * height > MAX_IMAGE_PIXELS:
        raise UnsafeMaterialPack("背景图片像素尺寸超过安全限制")


class MaterialPackManager:
    """Install, enumerate and apply built-in and custom UI material packs."""

    def __init__(self, data_directory: Path):
        """Create a manager whose user packs live in ``data/material_packs``."""
        self.data_directory = _guard_storage_root(Path(data_directory))
        self.storage_directory = _guard_storage_root(self.data_directory / "material_packs")
        self.last_errors: tuple[str, ...] = ()

    @classmethod
    def for_data_directory(cls, data_directory: Path) -> "MaterialPackManager":
        return cls(data_directory)

    def list_packs(self) -> list[MaterialPack]:
        packs = list(builtin_materials())
        errors: list[str] = []
        try:
            entries = sorted(self.storage_directory.iterdir(), key=lambda item: item.name.casefold())
        except OSError as exc:
            self.last_errors = (f"无法读取材质包目录：{exc}",)
            return packs
        for entry in entries:
            if entry.name.startswith(".aifo_pack_") or not entry.is_dir() or _is_link_like(entry):
                continue
            try:
                pack = self._load_custom(entry)
                if pack.id in BUILTIN_IDS:
                    raise UnsafeMaterialPack("自定义材质包不能覆盖内置材质")
                packs.append(pack)
            except (MaterialPackError, OSError, ValidationError, json.JSONDecodeError) as exc:
                errors.append(f"{entry.name}: {exc}")
        self.last_errors = tuple(errors)
        return packs

    def get_pack(self, pack_id: str) -> MaterialPack:
        if not _PACK_ID_RE.fullmatch(pack_id):
            raise MaterialPackNotFound("材质包 ID 无效")
        for pack in builtin_materials():
            if pack.id == pack_id:
                return pack
        target = self.storage_directory / pack_id
        if not target.is_dir() or _is_link_like(target):
            raise MaterialPackNotFound(f"找不到材质包：{pack_id}")
        try:
            return self._load_custom(target)
        except (OSError, ValidationError, json.JSONDecodeError) as exc:
            raise MaterialPackError(f"材质包已损坏：{exc}") from exc

    def _load_custom(self, directory: Path) -> MaterialPack:
        resolved = directory.resolve()
        if resolved.parent != self.storage_directory or _is_link_like(directory):
            raise UnsafeMaterialPack("材质包目录越界")
        manifest_path = directory / MANIFEST_NAME
        if _is_link_like(manifest_path) or not manifest_path.is_file():
            raise UnsafeMaterialPack("缺少安全的 manifest.json")
        with manifest_path.open("rb") as handle:
            raw = _read_bounded(handle, MAX_MANIFEST_BYTES)
        manifest = _parse_manifest(raw)
        if manifest.id != directory.name:
            raise UnsafeMaterialPack("manifest ID 与目录名不一致")
        background_path: Path | None = None
        allowed = {MANIFEST_NAME.casefold()}
        if manifest.background:
            allowed.add(unicodedata.normalize("NFC", manifest.background).casefold())
            candidate = directory / manifest.background
            if _is_link_like(candidate) or not candidate.is_file() or candidate.resolve().parent != resolved:
                raise UnsafeMaterialPack("背景文件不存在或越界")
            if candidate.stat().st_size > MAX_BACKGROUND_BYTES:
                raise UnsafeMaterialPack("背景文件超过大小限制")
            with candidate.open("rb") as handle:
                image = _read_bounded(handle, MAX_BACKGROUND_BYTES)
            _validate_image(image, manifest.background)
            background_path = candidate.resolve()
        # Installed packs are immutable data bundles; unexpected payloads are
        # rejected so no script/QSS can be smuggled beside the manifest.
        for item in directory.iterdir():
            if item.name.casefold() not in allowed or not item.is_file() or _is_link_like(item):
                raise UnsafeMaterialPack("材质包包含未声明或不安全的文件")
        return MaterialPack(
            manifest=manifest, source="custom", directory=resolved,
            background_path=background_path,
        )

    def import_pack(self, archive_path: Path, *, replace: bool = False) -> MaterialPack:
        archive_path = Path(archive_path)
        if archive_path.suffix.casefold() != PACK_EXTENSION:
            raise MaterialPackError(f"材质包必须使用 {PACK_EXTENSION} 扩展名")
        if _is_link_like(archive_path) or not archive_path.is_file():
            raise MaterialPackError("材质包文件不存在或不是普通文件")
        if archive_path.stat().st_size > MAX_ARCHIVE_BYTES:
            raise UnsafeMaterialPack("材质包压缩文件超过大小限制")

        try:
            with zipfile.ZipFile(archive_path) as archive:
                members = archive.infolist()
                if not members or len(members) > MAX_ARCHIVE_ENTRIES:
                    raise UnsafeMaterialPack("材质包文件数量异常")
                seen: set[str] = set()
                total = 0
                by_name: dict[str, zipfile.ZipInfo] = {}
                for info in members:
                    _validate_member_name(info.filename)
                    normalized = unicodedata.normalize("NFC", info.filename).casefold()
                    if normalized in seen:
                        raise UnsafeMaterialPack("材质包包含重复文件名")
                    seen.add(normalized)
                    if info.is_dir() or _zip_entry_is_link(info) or info.flag_bits & 0x1:
                        raise UnsafeMaterialPack("材质包包含链接、目录或加密项目")
                    if info.compress_type not in {zipfile.ZIP_STORED, zipfile.ZIP_DEFLATED}:
                        raise UnsafeMaterialPack("材质包使用了不支持的压缩方法")
                    total += info.file_size
                    if total > MAX_TOTAL_UNPACKED_BYTES:
                        raise UnsafeMaterialPack("材质包声明的解压大小超过限制")
                    if info.file_size and info.compress_size == 0:
                        raise UnsafeMaterialPack("材质包压缩比异常")
                    if info.compress_size and info.file_size / info.compress_size > MAX_COMPRESSION_RATIO:
                        raise UnsafeMaterialPack("材质包压缩比超过安全限制")
                    by_name[normalized] = info
                manifest_info = by_name.get(MANIFEST_NAME.casefold())
                if manifest_info is None or manifest_info.file_size > MAX_MANIFEST_BYTES:
                    raise UnsafeMaterialPack("缺少有效的 manifest.json")
                with archive.open(manifest_info) as handle:
                    raw_manifest = _read_bounded(handle, MAX_MANIFEST_BYTES)
                try:
                    manifest = _parse_manifest(raw_manifest)
                except (ValidationError, ValueError) as exc:
                    raise MaterialPackError(f"manifest.json 无效：{exc}") from exc
                if manifest.id in BUILTIN_IDS:
                    raise MaterialPackError("不能覆盖内置材质包")
                expected = {MANIFEST_NAME.casefold()}
                image_data: bytes | None = None
                if manifest.background:
                    image_key = unicodedata.normalize("NFC", manifest.background).casefold()
                    expected.add(image_key)
                    image_info = by_name.get(image_key)
                    if image_info is None or image_info.file_size > MAX_BACKGROUND_BYTES:
                        raise UnsafeMaterialPack("背景文件缺失或超过大小限制")
                    with archive.open(image_info) as handle:
                        image_data = _read_bounded(handle, MAX_BACKGROUND_BYTES)
                    _validate_image(image_data, manifest.background)
                if set(by_name) != expected:
                    raise UnsafeMaterialPack("材质包只能包含 manifest.json 和已声明的背景图片")
        except zipfile.BadZipFile as exc:
            raise MaterialPackError("材质包不是有效的 ZIP 文件") from exc
        except OSError as exc:
            raise MaterialPackError(f"无法读取材质包：{exc}") from exc

        target = self.storage_directory / manifest.id
        if target.exists() and not replace:
            raise MaterialPackError(f"材质包 {manifest.id} 已存在")
        if target.exists() and (_is_link_like(target) or not target.is_dir()):
            raise UnsafeMaterialPack("现有材质包目录不安全")

        stage = Path(tempfile.mkdtemp(prefix=".aifo_pack_", dir=self.storage_directory))
        backup: Path | None = None
        try:
            (stage / MANIFEST_NAME).write_bytes(raw_manifest)
            if manifest.background and image_data is not None:
                (stage / manifest.background).write_bytes(image_data)
            # Validate the exact on-disk representation before publishing it.
            self._load_custom_staged(stage, manifest.id)
            if target.exists():
                backup = self.storage_directory / f".aifo_pack_backup_{manifest.id}_{os.getpid()}"
                if backup.exists():
                    raise MaterialPackError("材质包备份目录冲突")
                target.rename(backup)
            stage.rename(target)
            if backup is not None:
                _remove_tree_without_following_links(backup)
            return self._load_custom(target)
        except Exception:
            if target.exists() and backup is not None:
                _remove_tree_without_following_links(target)
            if backup is not None and backup.exists():
                backup.rename(target)
            raise
        finally:
            if stage.exists():
                _remove_tree_without_following_links(stage)

    def _load_custom_staged(self, stage: Path, expected_id: str) -> MaterialPack:
        # Staging directory name intentionally differs from the pack ID.
        manifest_path = stage / MANIFEST_NAME
        raw = manifest_path.read_bytes()
        manifest = _parse_manifest(raw)
        if manifest.id != expected_id:
            raise UnsafeMaterialPack("材质包 ID 在导入期间发生变化")
        background_path = stage / manifest.background if manifest.background else None
        if background_path is not None:
            _validate_image(background_path.read_bytes(), manifest.background or "")
        return MaterialPack(
            manifest=manifest, source="custom", directory=stage.resolve(),
            background_path=background_path.resolve() if background_path else None,
        )

    def delete_pack(self, pack_id: str) -> None:
        if pack_id in BUILTIN_IDS:
            raise MaterialPackError("内置材质包不能删除")
        if not _PACK_ID_RE.fullmatch(pack_id):
            raise MaterialPackError("材质包 ID 无效")
        target = self.storage_directory / pack_id
        if not target.exists():
            raise MaterialPackNotFound(f"找不到材质包：{pack_id}")
        if target.resolve().parent != self.storage_directory or _is_link_like(target) or not target.is_dir():
            raise UnsafeMaterialPack("材质包目录不安全")
        _remove_tree_without_following_links(target)

    def stylesheet(self, pack_or_id: MaterialPack | str) -> str:
        pack = self.get_pack(pack_or_id) if isinstance(pack_or_id, str) else pack_or_id
        return "" if pack.id == "default" else build_stylesheet(pack)

    def apply(self, application: object | None, pack_or_id: MaterialPack | str) -> str:
        """Apply a pack to a QApplication/QWidget-like object and return its ID."""
        pack = self.get_pack(pack_or_id) if isinstance(pack_or_id, str) else pack_or_id
        stylesheet = "" if pack.id == "default" else build_stylesheet(pack)
        if application is not None:
            setter = getattr(application, "setStyleSheet", None)
            if not callable(setter):
                raise TypeError("application 必须提供 setStyleSheet(str)")
            setter(stylesheet)
        return pack.id

    def create_example_pack(
        self,
        destination: Path,
        *,
        pack_id: str = "my-material",
        name: str = "My Material",
    ) -> Path:
        """Create an importable, script-free example package for users."""
        manifest = MaterialManifest(
            id=pack_id, name=name, author="User",
            description="可编辑颜色值后重新导入的示例材质包。",
            colors=_BUILTIN_MANIFESTS[0].colors,
        )
        destination = Path(destination)
        if destination.suffix.casefold() != PACK_EXTENSION:
            destination = destination.with_suffix(PACK_EXTENSION)
        destination.parent.mkdir(parents=True, exist_ok=True)
        if destination.exists():
            raise MaterialPackError("示例材质包目标文件已存在")
        payload = manifest.model_dump_json(indent=2).encode("utf-8")
        info = zipfile.ZipInfo(MANIFEST_NAME)
        info.date_time = (2026, 1, 1, 0, 0, 0)
        info.compress_type = zipfile.ZIP_DEFLATED
        info.external_attr = 0o100600 << 16
        with zipfile.ZipFile(destination, "x") as archive:
            archive.writestr(info, payload)
        return destination.resolve()

    def create_example(
        self,
        destination: Path,
        *,
        pack_id: str = "my-material",
        name: str = "My Material",
    ) -> Path:
        return self.create_example_pack(destination, pack_id=pack_id, name=name)


def _remove_tree_without_following_links(root: Path) -> None:
    """Delete a pack directory without traversing symlinks or junctions."""
    if _is_link_like(root):
        if root.is_dir():
            root.rmdir()
        else:
            root.unlink(missing_ok=True)
        return
    if not root.exists():
        return
    for entry in os.scandir(root):
        path = Path(entry.path)
        if entry.is_symlink() or _is_link_like(path):
            if entry.is_dir(follow_symlinks=False):
                path.rmdir()
            else:
                path.unlink(missing_ok=True)
        elif entry.is_dir(follow_symlinks=False):
            _remove_tree_without_following_links(path)
        else:
            path.unlink(missing_ok=True)
    root.rmdir()


def build_stylesheet(pack: MaterialPack) -> str:
    """Generate Qt stylesheet text using only already-validated tokens."""
    c = pack.manifest.colors
    background_rule = ""
    if pack.background_path is not None:
        path = pack.background_path.resolve()
        if pack.directory is None or path.parent != pack.directory.resolve() or _is_link_like(path):
            raise UnsafeMaterialPack("背景文件路径越界")
        # pathlib.as_uri percent-encodes QSS punctuation; the manifest never
        # controls selectors or property names.
        uri = path.as_uri()
        repeat = "repeat" if pack.manifest.background_mode == "tile" else "no-repeat"
        position = "center" if pack.manifest.background_mode in {"cover", "center"} else "top left"
        background_rule = f'background-image: url("{uri}"); background-repeat: {repeat}; background-position: {position};'
    return f"""
QMainWindow {{ background-color: {c.window}; {background_rule} }}
QWidget {{ color: {c.text}; }}
QWidget#centralWidget {{ background-color: {c.window}; {background_rule} }}
QDialog {{ background-color: {c.window}; }}
QMenuBar {{ background-color: {c.panel}; color: {c.text}; border-bottom: 1px solid {c.border}; }}
QMenuBar::item {{ background: transparent; padding: 5px 9px; }}
QMenuBar::item:selected {{ background-color: {c.accent}; color: {c.selection_text}; border-radius: 3px; }}
QStatusBar {{ background-color: {c.panel}; color: {c.muted_text}; border-top: 1px solid {c.border}; }}
QFrame[role="panel"], QGroupBox, QTabWidget::pane {{ background-color: {c.panel}; border: 1px solid {c.border}; border-radius: 6px; }}
QGroupBox {{ margin-top: 10px; padding-top: 10px; }}
QGroupBox::title {{ subcontrol-origin: margin; left: 9px; padding: 0 4px; color: {c.muted_text}; }}
QLineEdit, QTextEdit, QPlainTextEdit, QSpinBox, QDoubleSpinBox, QComboBox, QListView, QTreeView, QTableView {{
    background-color: {c.input}; color: {c.text}; border: 1px solid {c.border}; border-radius: 4px; padding: 4px;
    selection-background-color: {c.accent}; selection-color: {c.selection_text};
}}
QLineEdit:focus, QTextEdit:focus, QPlainTextEdit:focus, QSpinBox:focus, QDoubleSpinBox:focus, QComboBox:focus, QListView:focus, QTreeView:focus, QTableView:focus {{ border: 2px solid {c.accent}; }}
QTableView, QTreeView {{ alternate-background-color: {c.elevated}; gridline-color: {c.border}; }}
QHeaderView::section {{ background-color: {c.elevated}; color: {c.text}; border: 0; border-right: 1px solid {c.border}; border-bottom: 1px solid {c.border}; padding: 6px; }}
QTableCornerButton::section {{ background-color: {c.elevated}; border: 0; border-right: 1px solid {c.border}; border-bottom: 1px solid {c.border}; }}
QPushButton {{ background-color: {c.accent}; color: {c.selection_text}; border: 0; border-radius: 5px; padding: 6px 12px; }}
QPushButton:hover {{ background-color: {c.accent_hover}; }}
QPushButton:pressed {{ background-color: {c.accent_pressed}; }}
QPushButton:disabled {{ background-color: {c.border}; color: {c.muted_text}; }}
QPushButton:focus {{ border: 2px solid {c.text}; padding: 4px 10px; }}
QToolButton {{ background-color: {c.elevated}; color: {c.text}; border: 1px solid {c.border}; border-radius: 4px; padding: 4px; }}
QToolButton:hover {{ border-color: {c.accent}; }}
QTabBar::tab {{ background-color: {c.elevated}; color: {c.muted_text}; border: 1px solid {c.border}; padding: 7px 12px; }}
QTabBar::tab:selected {{ background-color: {c.panel}; color: {c.accent}; border-bottom-color: {c.panel}; }}
QMenu, QToolTip {{ background-color: {c.panel}; color: {c.text}; border: 1px solid {c.border}; }}
QMenu::item:selected {{ background-color: {c.accent}; color: {c.selection_text}; }}
QProgressBar {{ background-color: {c.input}; border: 1px solid {c.border}; border-radius: 4px; text-align: center; }}
QProgressBar::chunk {{ background-color: {c.accent}; border-radius: 3px; }}
QCheckBox::indicator, QRadioButton::indicator {{ width: 15px; height: 15px; }}
QLabel[role="muted"] {{ color: {c.muted_text}; }}
QLabel[role="notice"] {{ background-color: {c.elevated}; color: {c.muted_text}; border: 1px solid {c.border}; border-radius: 4px; padding: 8px; }}
QLabel[status="success"] {{ color: {c.success}; }}
QLabel[status="warning"] {{ color: {c.warning}; }}
QLabel[status="danger"] {{ color: {c.danger}; }}
QScrollBar:vertical, QScrollBar:horizontal {{ background: {c.window}; border: 0; }}
QScrollBar::handle:vertical, QScrollBar::handle:horizontal {{ background: {c.muted_text}; border-radius: 4px; min-height: 24px; min-width: 24px; }}
""".strip()


__all__ = [
    "AppliedMaterial", "BUILTIN_IDS", "ColorTokens", "MaterialManifest", "MaterialPack",
    "MaterialPackError", "MaterialPackManager", "MaterialPackNotFound", "UnsafeMaterialPack",
    "build_stylesheet", "builtin_materials",
]
